// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: ClimaTempo

#include "ui.h"
#include "lvgl.h"

extern const lv_font_t lv_font_montserrat_42;
lv_chart_series_t * ui_Chart2_series_1;
lv_chart_series_t * ui_Chart2_series_2;
lv_chart_series_t * ui_Chart2_series_3;

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backgroundImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_backgroundImage, &ui_img_background_png);
    lv_obj_set_width(ui_backgroundImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backgroundImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backgroundImage, -2);
    lv_obj_set_y(ui_backgroundImage, -5);
    lv_obj_set_align(ui_backgroundImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backgroundImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backgroundImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTemp, -152);
    lv_obj_set_y(ui_labelTemp, -95);
    lv_obj_set_align(ui_labelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp, "0.0 °C");
    lv_obj_set_style_text_color(ui_labelTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTemp, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelHum = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelHum, 152);
    lv_obj_set_y(ui_labelHum, -95);
    lv_obj_set_align(ui_labelHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelHum, "0.0 %");
    lv_obj_set_style_text_color(ui_labelHum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelHum, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -200);
    lv_obj_set_y(ui_Label1, -136);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Temperatura");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 51);
    lv_obj_set_y(ui_Label2, -136);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Umidade");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_Chart2, 453);
    lv_obj_set_height(ui_Chart2, 204);
    lv_obj_set_x(ui_Chart2, -6);
    lv_obj_set_y(ui_Chart2, 103);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, -10, 10);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, -10, 10);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xD40B0B),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    ui_Chart2_series_2 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x0CE05B),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart2_series_2_array[] = { 0, 0, 2, 40, 50, 40, 90, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_2, ui_Chart2_series_2_array);
    ui_Chart2_series_3 = lv_chart_add_series(ui_Chart2, lv_color_hex(0xE8FE0B),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart2_series_3_array[] = { 0, 8, 50, 40, 0, 80, 40, 70, 10, 0, 2 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_3, ui_Chart2_series_3_array);
    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -248);
    lv_obj_set_y(ui_Label3, -15);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Accel");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -200);
    lv_obj_set_y(ui_Label4, -176);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Pacotes Recebidos");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 54);
    lv_obj_set_y(ui_Label5, -176);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "LoRa RSSI");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
