// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button, 184);
    lv_obj_set_height(ui_Button, 50);
    lv_obj_set_x(ui_Button, -40);
    lv_obj_set_y(ui_Button, 4);
    lv_obj_set_align(ui_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Button, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
